config/routes.rb
MyThreeBest::Application.routes.draw do

  # - Homepage
  root :to => "pages#index"

  # - How it works
  match "/invite_sent" => "pages#facebook_callback", :as => :facebook_callback

  # - Auth Routes
  devise_for :users do
    get "/login", :to => redirect("/auth/facebook"), :as => :new_user_session
    get "/logout", :to => "devise/sessions#destroy"
  end

  match "/auth/:provider/callback" => "sessions#create"

  # - Friends
  #resources :friends
  #match "/friends" => "friends#index", :as => :friends_show

  # -  Invites routes
  match "/invite/all" => "invites#all", :as => :invite_all
  match "/invite/:user_id" => "invites#create", :as => :invite_friend
  match "/invite/:user_id/new" => "invites#new", :as => :new_invite
  #resources :invites

  # - Vote Routes
  match "/votes" => "votes#index", :as => :votes
  match "/votes/:user_id" => "votes#show", :as => :friend_votes
  match "/vote/:user_id/save" => "votes#create", :as => :save_vote
  match "/vote/:user_id/:token" => "votes#new", :as => :new_vote
  match "/unvote/:user_id/:photo_id" => "votes#destroy", :as => :delete_vote

  resources :users, :only => [:index, :update] do
    resources :photos, :only => [:index]
  end
  #match "/users/:id" => "users#update", :as => :user

  match "/:public_page_url" => "users#show", :as => :public_profile
end

app/views/shared/_best_photo.html.haml
.frame
  - if photo
    = image_tag photo.preview_url, :width => "212"
  - else
    = image_tag "question_mark.png", :class => "question_mark"
- if photo
  %a{:href => "#"} See Votes
- else
  %a{:href => "#", :class => "disabled_button"} See Votes

app/views/shared/_best_photo_small.html.haml
- if photo
  = image_tag photo.preview_url, :width => 66
  %a{:href => "#"} See Votes
- else
  = image_tag "question_mark.png", :width => 66
  %a{:href => "#", :class => "disabled_button"} See Votes

app/views/shared/_footer.html.haml
- css_class ||= ""
#footer{:class => css_class}
  .left_link
    %p &copy; 2011 my three best Inc.
    %ul
      %li.first
        %a{:href => "#"} Terms
      %li
        %a{:href => "#"} Privacy

app/views/shared/_header.html.haml
#header
  %span.logo
    = link_to image_tag("logo.png"), root_path
  .work_top
    %ul
      - if signed_in?
        %li.first Hi, #{current_user.first_name}!
      - else
        %li.first Hi, Visitor!
      %li.last
        - if signed_in?
          = link_to "Log Out", logout_path
        - else
          = link_to "Log in", new_user_session_path

app/views/shared/_javascripts.html.haml
= javascript_include_tag :defaults
= javascript_include_tag "pageclass/#{controller.controller_name}"

app/views/shared/_menu.html.haml
.work_menu
  .work_menu_bg
    .work_menu_left
      .work_menu_right
        %ul
          %li.first
            %a{:href => root_path, :class => ((active == "dashboard") ? "active" : "" )}
              %span Invite Friends
          %li
            %a{:href => "/votes/friends", :class => ((active == "friend_votes") ? "active" : "" )}
              %span See Friends Votes
          %li
            %a{:href => public_profile_path(current_user.public_page_url), :class => ((active == "public_page") ? "active" : "" )}
              %span Show the World
          %li
            %a{:href => "/votes", :class => ((active == "see_votes") ? "active" : "" )}
              %span See Vote

app/views/shared/_photo_vote.html.haml
.friends_row{:class => css_class}
  .friends_col01
    = image_tag photo.preview_url, :width => 109
  .friends_col02
    %h3
      %strong= photo.voters.first.full_name
      - if photo.voters.count > 1
        and
        %strong= (photo.voters.count - 1)
        others vote this!
      - else
        vote this!
      - photo.voters.each_slice(11) do |row|
        %ul
          - row.each do |voter|
            %li
              = image_tag voter.profile_picture, :width => 35, :height => 35

app/views/shared/_public_page_photo.html.haml
- if photo
  = image_tag photo.preview_url, :width => "212"
- else
  = image_tag "question_mark.png", :width => "212"

app/views/shared/_three_best.html.haml
.invite_bg_repeat.pad02
  .invite_top
    .invite_bottom
      .invite_main
        %h2 My Current Three Best
        %ul
          %li.first
            = render :partial => "shared/best_photo", :locals => {:photo => current_user.top_photo_one}
          %li
            = render :partial => "shared/best_photo", :locals => {:photo => current_user.top_photo_two}
          %li
            = render :partial => "shared/best_photo", :locals => {:photo => current_user.top_photo_three}
        %h2 Show the World
        = link_to "mythreebest.com/#{current_user.public_page_url}", public_profile_url(current_user.public_page_url), :class => "link"
        %span.world
          = simple_form_for current_user, :remote => true do |f|
            = f.input :public_page, :label => 'Enable Show to the world'

:javascript
  $(document).ready(function() {
      $("#user_public_page").click(function() {
          $(".simple_form").submit();
      });
  });

app/views/shared/_user_avatar.html.haml
.invite_bg_repeat
  .invite_top
    .invite_bottom
      .invite_main
        = image_tag current_user.profile_picture
        %p #{current_user.first_name}