config/routes.rb
MyThreeBest::Application.routes.draw do

  # - Homepage
  root :to => "pages#index"

  # - How it works
  match "/invite_sent" => "pages#facebook_callback", :as => :facebook_callback

  # - Auth Routes
  devise_for :users do
    get "/login", :to => redirect("/auth/facebook"), :as => :new_user_session
    get "/logout", :to => "devise/sessions#destroy"
  end

  match "/auth/:provider/callback" => "sessions#create"

  # - Friends
  #resources :friends
  #match "/friends" => "friends#index", :as => :friends_show

  # -  Invites routes
  match "/invite/all" => "invites#all", :as => :invite_all
  match "/invite/:user_id" => "invites#create", :as => :invite_friend
  match "/invite/:user_id/new" => "invites#new", :as => :new_invite
  #resources :invites

  # - Vote Routes
  match "/votes" => "votes#index", :as => :votes
  match "/votes/:user_id" => "votes#show", :as => :friend_votes
  match "/vote/:user_id/save" => "votes#create", :as => :save_vote
  match "/vote/:user_id/:token" => "votes#new", :as => :new_vote
  match "/unvote/:user_id/:photo_id" => "votes#destroy", :as => :delete_vote

  resources :users, :only => [:index, :update] do
    resources :photos, :only => [:index]
  end
  #match "/users/:id" => "users#update", :as => :user

  match "/:public_page_url" => "users#show", :as => :public_profile
end

app/views/pages/dashboard.html.haml
%body
  #layout
    = render "shared/header"
    #body_container
      .work_container
        .work_bg_repeat
          .work_bg_top
            .work_bg_bottom
              .work_main
                = render :partial => "shared/menu", :locals => {:active => "dashboard"}
                .invite_left
                  = render "shared/user_avatar"
                  = render "shared/three_best"
                .invite_right
                  .invite_right_bg
                    .invite_right_top
                      .invite_right_bottom
                        .invite_outer
                          .banner
                            %h2 
                              Invite your friend to vote on your photos
                            %br
                            %script{:src => "http://connect.facebook.net/en_US/all.js#xfbml=1"}
                            .send_button
                              %p
                                = link_to image_tag("sendPersonalInvite.png"),
                                  "https://www.facebook.com/dialog/send?app_id=#{FacebookConfig['app_id']}&name=My%20Three%20Best&link=#{new_vote_url(current_user, current_user.token)}&redirect_uri=#{facebook_callback_url}&picture=#{current_user.profile_picture}&description=Hey!!!%20Vote%20for%20My%20Three%20Best%20photos%20now!!!&display=popup",
                                  :class => "popup"
                            %br
                            %p
                            = link_to image_tag("postWall.png"), invite_all_path, :remote => true, :id => "invite-all"
                          .row
                            - if @friends.empty?
                              %h2 You don't have any votes yet, invite more friends to vote!!!
                            - else
                              %h2 Recent Votes
                          #rows
                            - @friends.each_slice(2) do |friend|
                              .row
                                %ul
                                  %li.first
                                    %img{:src => friend[0].profile_picture}
                                    %h3
                                      %a{:href => "#"}= friend[0].full_name
                                      %p
                                        = link_to "View #{friend[0].first_name}'s votes »", friend_votes_path(friend[0].id)
                                  - if friend[1]
                                    %li
                                      %img{:src => friend[1].profile_picture}
                                      %h3
                                        %a{:href => "#"}= friend[1].full_name
                                        %p
                                          = link_to "View #{friend[1].first_name}'s votes »", friend_votes_path(friend[1].id)
                      %span.clear
        %span.clear
    = render :partial => "shared/footer", :locals => {:css_class => "pad1"}

:javascript
  $(document).ready(function() {
      //ajaxInvite();
      $("#invite-all").bind("ajax:success", function(event, data, status, xhr) {
          alert('The Invite will be posted in your wall soon!!');
      });
      //getFriends();
      //window.getFriendsInterval = window.setInterval(getFriends, 3000);

      $(".popup").click(function(evt) {
          evt.preventDefault();
          popip = window.open($(this).attr('href'),'My Three Best','height=320,width=580');
      });
  });

app/views/pages/facebook_callback.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
    %title MyThreeBest
    :javascript
      window.close();
  %body

app/views/pages/index.html.haml
%body
  #layout
    #header
      %span.logo
        = link_to image_tag("logo.png"), root_path
      .login
        = link_to image_tag("login_icon.gif"), "/auth/facebook"
        = link_to "login", "/auth/facebook"
      %h2 Invite your friends to select your three best photos!
    #crousal
      .belt
        %div
          .next
            = link_to image_tag("next_arrow.png"), "#"
        %div
          .prev
            = link_to image_tag("prev_arrow.png"), "#"
        .panel
          %ul
            %li.first
              = image_tag "pict01.jpg"
            %li
              = image_tag "pict02.jpg"
            %li
              = image_tag "pict03.jpg"
    .facebook_login
      %a{:href => "/auth/facebook"}
        = image_tag "facebook_icon.gif"
        %span.blue_bg
          %span.blue_bg_right
            %strong Login with Facebook and Start now!
    .bottom_box
      .box_bg_repeat
        .box_bg_top
          .box_bg_bottom
            .box_main
              %ul
                %li.first
                  .common_box_bg
                    .common_box_top
                      .common_box_bottom
                        .common_box_main
                          .common_box_inner.inner_bg03
                            %h2 Invite your friends
                            %p
                              %strong Kelly
                              is inviting her 130
                              %br
                              friends to vote her 3 best
                            %ul
                              %li.last
                                = image_tag "small_img01.gif"
                              %li
                                = image_tag "small_img02.gif"
                              %li
                                = image_tag "small_img03.gif"
                              %li
                                = image_tag "small_img04.gif"
                              %li
                                = image_tag "small_img05.gif"
                              %li
                                = image_tag "small_img06.gif"
                          %span.clear
                %li
                  .common_box_bg
                    .common_box_top
                      .common_box_bottom
                        .common_box_main
                          .common_box_inner.inner_bg02
                            %h2.head02 Viewing Photos
                            = image_tag "viewing_photos.png"
                %li
                  .common_box_bg
                    .common_box_top
                      .common_box_bottom
                        .common_box_main
                          .common_box_inner.inner_bg01
                            %h2.head03 Vote Your 3 Best
                            .vote
                              .vote_img
                                .vote_bg
                                  = image_tag "img01.gif"
                              .vote_img02
                                .vote_bg
                                  = image_tag "img02.gif"
                              .vote_img03
                                .vote_bg
                                  = image_tag "img03.gif"
                          %span.clear
                %li
                  .common_box_bg
                    .common_box_top
                      .common_box_bottom
                        .common_box_main
                          .inner_bg_repeat
                            .common_box_inner.inner_bg04
                              %h2.head04 See Friends Vote
                              = image_tag "vote.png"
      %span.clear
    = render "shared/footer"