config/routes.rb
MyThreeBest::Application.routes.draw do

  # - Homepage
  root :to => "pages#index"

  # - How it works
  match "/invite_sent" => "pages#facebook_callback", :as => :facebook_callback

  # - Auth Routes
  devise_for :users do
    get "/login", :to => redirect("/auth/facebook"), :as => :new_user_session
    get "/logout", :to => "devise/sessions#destroy"
  end

  match "/auth/:provider/callback" => "sessions#create"

  # - Friends
  #resources :friends
  #match "/friends" => "friends#index", :as => :friends_show

  # -  Invites routes
  match "/invite/all" => "invites#all", :as => :invite_all
  match "/invite/:user_id" => "invites#create", :as => :invite_friend
  match "/invite/:user_id/new" => "invites#new", :as => :new_invite
  #resources :invites

  # - Vote Routes
  match "/votes" => "votes#index", :as => :votes
  match "/votes/:user_id" => "votes#show", :as => :friend_votes
  match "/vote/:user_id/save" => "votes#create", :as => :save_vote
  match "/vote/:user_id/:token" => "votes#new", :as => :new_vote
  match "/unvote/:user_id/:photo_id" => "votes#destroy", :as => :delete_vote

  resources :users, :only => [:index, :update] do
    resources :photos, :only => [:index]
  end
  #match "/users/:id" => "users#update", :as => :user

  match "/:public_page_url" => "users#show", :as => :public_profile
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  # - Associations
  belongs_to :photo
  belongs_to :voter, :class_name => "User"

  # - Validations
  validates_uniqueness_of :voter_id, :scope => :photo_id

  # - Callbacks
  after_create :update_photo_votes
  after_destroy :update_photo_votes

  def update_photo_votes
    photo = self.photo
    photo.update_attribute(:total_votes, photo.votes.count)
    perform_top_calculation
  end

  private

  def perform_top_calculation
    job_id = TopCalculation.create(:user_id => self.photo.user.id)
    Rails.logger.info "[Queued Job with id #{job_id}]"
  end

end



# == Schema Information
#
# Table name: votes
#
#  id         :integer         not null, primary key
#  voter_id   :integer         not null
#  photo_id   :integer         not null
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :authorize_user!, :only => :new
  before_filter :authenticate_user!, :except => :new

  def index
    @photos = current_user.voted_photos.page(params[:page]).per(5).includes(:voters)
    respond_to do |format|
      format.html
    end
  end

  def show
    @voters_with_votes = Kaminari.paginate_array(current_user.voters_with_votes).page(params[:page]).per(5)
    respond_to do |format|
      format.html
    end
  end

  def new
    @user = User.find(params[:user_id])
    respond_to do |format|
      if facebook_request?
        format.html { render :facebook }
      else
        authenticate_user! unless facebook_request?
        voted_photos = current_user.votes_for(@user)
        @first_voted  = voted_photos[0] rescue nil
        @second_voted = voted_photos[1] rescue nil
        @third_voted  = voted_photos[2] rescue nil
        #@photos = current_user.photos_for_friend(@user, params[:page])
        @photos = @user.photos.page(params[:page]).per(20).sort_by{|photo| photo.priority}
        format.html
        format.json { render :json => @photos }
      end
    end
  end

  def create
    photos_ids = params[:vote].delete_if{|id| id == ""}
    @photos = photos_ids.map{|id| Photo.find(id)}
    if current_user.vote(@photos)
      respond_to do |format|
        format.js { render :json => true }
      end
    end
  end

  def destroy
    @photo = Photo.find(params[:photo_id])
    if current_user.unvote(@photo)
      respond_to do |format|
        format.js{ render :json => true }
      end
    end
  end

  def facebook_request?
    Rails.logger.info "*"*50
    Rails.logger.info request.env['HTTP_USER_AGENT']
    request.env['HTTP_USER_AGENT'] == "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_selected_photo.html.haml
= hidden_field_tag "vote[]", (photo.id rescue nil), :id => class_name
- if photo
  %a.active{:href => "#", :class => "select-photo"}
    %span Replace
  .img_frame
    = image_tag photo.preview_url, :class => "selected-photo-img", :width => "169"
- else
  %a{:href => "#", :class => "select-photo"}
    %span Choose
  = image_tag "vote_img0#{number}.gif", :class => "selected-photo-img", :width => "169"

app/views/votes/facebook.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %meta{:content => "text/html; charset=iso-8859-1", "http-equiv" => "Content-Type"}/
    %meta{:property => "og:title", :content => "My Three Best"}/
    %meta{:property => "og:image", :content => @user.profile_picture}/
    %meta{:property => "og:description", :content => "Vote My Three Best Photos!!!"}
    %title MyThreeBest
  %body
    #content
      %p Vote My Three Best Photos!!!

app/views/votes/index.html.haml
%body
  #layout
    = render "shared/header"
    #body_container
      .work_container
        .work_bg_repeat
          .work_bg_top
            .work_bg_bottom
              .work_main
                = render :partial => "shared/menu", :locals => {:active => "see_votes"}
                .invite_left
                  = render "shared/user_avatar"
                  = render "shared/three_best"
                .invite_right
                  .invite_right_bg
                    .invite_right_top
                      .invite_right_bottom
                        .invite_outer01
                          - if @photos.empty?
                            .friends_votes
                              %h2{:class => "brown_text"} You don't have votes yet, invite more friends!!!
                          - else
                            .friends_votes
                              %h2{:class => "brown_text"} Your Votes from Friends
                              - @photos.each do |photo|
                                = render :partial => "shared/photo_vote", :locals => {:css_class => "pad03", :photo => photo}
                            .paging
                              = paginate @photos, :left => 6, :right => 1
                      %span.clear
        %span.clear
    = render :partial => "shared/footer", :locals => {:css_class => "pad1"}

app/views/votes/new.html.haml
- content_for :meta do
  %meta{:property => "og:title", :content => "My Three Best"}/
  %meta{:property => "og:image", :content => @user.profile_picture}/
  %meta{:property => "og:description", :content => "Vote My Three Best Photos!!!"}


%body
  #layout
    = render "shared/header"
    #body_container
      .work_container
        .work_bg_repeat
          .work_bg_top
            .work_bg_bottom
              .work_main
                %h4
                  Choose
                  %strong #{@user.full_name}
                  Three Best Photos
                %p.head_text
                  Sed dapibus convallis molestie &middot;
                  %em Nullam et neque eu dolor eleifend faucibus.
                .black_box
                  .black_box_bg
                    .black_box_top
                      .black_box_bottom
                        .black_box_main
                          .photos_box
                            #fantasticFlow.ContentFlow
                              .loadIndicator
                                .indicator
                              .flow
                                - @photos.each do |photo|
                                  = image_tag photo.preview_url, :id => photo.id, :class => "item", :title => photo.title
                              .globalCaption.grayCaption
                              .scrollbar
                                .slider
                                  .position.grayCaption
                          .choose_img_sec
                            #try_container
                              .try_outer
                                .try_top{:class => "png"}
                                  %span{:class => "clear"}
                                .try_bg{:class => "png"}
                                  .try_main
                                    %a{:href => "#", :class => "close"}
                                    %h2 Thanks! Would you like to invite your friends to choose your <strong>Three Best</strong> Photos?
                                    %ul
                                      %li{:class => "first"}
                                        = link_to "Yes", root_path, :class => "yes"
                                      %li
                                        = link_to "Skip - Take me to Facebook", "https://facebook.com", :class => "skip"
                                .try_bottom{:class => "png"}
                            = form_tag(save_vote_path, :remote => true, :id => "save-vote") do
                              %ul
                                %li.first
                                  = render :partial => "selected_photo", :locals => {:photo => (@first_voted.photo rescue nil), :class_name => "first_photo_vote", :number => 1}
                                %li
                                  = render :partial => "selected_photo", :locals => {:photo => (@second_voted.photo rescue nil), :class_name => "second_photo_vote", :number => 2}
                                %li
                                  = render :partial => "selected_photo", :locals => {:photo => (@third_voted.photo rescue nil), :class_name => "third_photo_vote", :number => 3}
                              = hidden_field_tag 'vote_comment'
                            .tool_tip
                              %a{:href => "#"}
                                = image_tag "icon01.gif"
                              .tool_tip_input
                                %input{:name => "message", :type => "text", :value => "What's on your mind?"}/
                          %a.finished{:href => "#"} Click Here When Finished
                      %span.clear
        %span.clear
    = render :partial => "shared/footer", :locals => {:css_class => "pad1"}

  :javascript
    var fantasticFlow = new ContentFlow('fantasticFlow');
    var photosPage = 1;
    var loadInterval;
    $(document).ready(function() {
        loadInterval = setInterval(loadPage, 1000);
        $(".select-photo").click(function(event) {
            event.preventDefault();
            var selected = $(".active canvas");
            var photoId = selected.attr('id');
            var photo = selected.attr('src');
            var alreadySelected = $(".selected-photo-img[src='"+photo+"']");
            if (alreadySelected.length == 0) {
                $(this).parent().find(".selected-photo-img").attr("src", photo);
                $(this).find(".selected-photo-img").wrap('<div class="img_frame" />');
                $(this).parent().find("input").val(photoId);
                $(this).find("span").text("Replace");
                $(this).addClass("active");
            } else {
                alert("The photo is selected already!!");
            }
        });
        $(".finished").click(function(event) {
            event.preventDefault();
            $("#save-vote").submit();
        });
        $("#save-vote").bind("ajax:success", function(event, data, status, xhr) {
            $("#try_container").css('display', 'block');
        });
        $(".close").click(function(event) {
            event.preventDefault();
            $("#try_container").css('display', 'none');
        });
        $(".tool_tip_input input").click(function(event) {
            $(this).val("");
        });
        $(".tool_tip_input input").blur(function() {
            if($(this).val() == "") {
                $(this).val("What's on your mind?");
            }
        });
    });

app/views/votes/show.html.haml
%body
  #layout
    = render "shared/header"
    #body_container
      .work_container
        .work_bg_repeat
          .work_bg_top
            .work_bg_bottom
              .work_main
                = render :partial => "shared/menu", :locals => {:active => "friend_votes"}
                .invite_left
                  = render "shared/user_avatar"
                  = render "shared/three_best"
                .invite_right
                  .invite_right_bg
                    .invite_right_top
                      .invite_right_bottom
                        .invite_outer
                          .votes
                            - if @voters_with_votes.empty?
                              %h2{:class => "brown_text"} You don't have votes yet, invite more friends!!!
                            - else
                              - @voters_with_votes.each do |voter_with_vote|
                                - voter_with_vote.each do |voter, votes|
                                  .votes_row
                                    .top_sec
                                      = image_tag voter.profile_picture, :width => 32, :height => 32
                                      %h2
                                        = voter.full_name
                                        %strong Votes You
                                      %em= "#{time_ago_in_words(votes.first.created_at)} ago"
                                    %ul
                                      - if votes[0]
                                        %li.first
                                          = image_tag votes[0].photo.preview_url, :width => 130
                                      - if votes[1]
                                        %li
                                          = image_tag votes[1].photo.preview_url, :width => 130
                                      - if votes[2]
                                        %li
                                          = image_tag votes[2].photo.preview_url, :width => 130
                          .paging
                            = paginate @voters_with_votes, :left => 6, :right => 1
                      %span.clear
        %span.clear
    = render :partial => "shared/footer", :locals => {:css_class => "pad1"}